### ISSUE TITLE
Crash with umlauts - ORA-01426: numeric overflow

### ISSUE THREAD

**Issue by NorbertR** [CruiserX/sha256_plsql#2]
Hello,

nice project, but I have problems with umlauts and special characters like 'ß'

select sha256.encrypt('Ä') from dual;

ORA-01426: numeric overflow
ORA-06512: at "DOWNER.SHA256", line 384
ORA-06512: at "DOWNER.SHA256", line 511

select sha256.encrypt('ß') from dual;

ORA-01426: numeric overflow
ORA-06512: at "DOWNER.SHA256", line 384
ORA-06512: at "DOWNER.SHA256", line 511

cu Norbert

**Comment by CruiserX** [comment]
Sorry.
I did not consider special charactors or national languages.
I'll fix it soon.

**Comment by bgsridhara** [comment]
Hi ,

We are trying to run the sha256.encrypt for the SPECIAL CHARACTER And its throwing an error,

could you please share the script if you have created for special character.

**Comment by CruiserX** [comment]
I changed internal variable to raw type.
It will work.
