### ISSUE TITLE
Wrong hash when raw length > 64

### ISSUE THREAD

**Issue by chakhdin** [CruiserX/sha256_plsql#4]
select sha256.ENCRYPT('very very very very very very very very very very very long message') from dual;
produces
529ce48578763f67ec86fe04fee5e0ecbd4954d6b09baa5109494ece75d04609
while it should be 
0d6930576859630d2254bef86b875767ea2c9e674ad7110ed6882ca263b05194

select sha256.ENCRYPT('very very very very very very very very very very long message') from dual;
correctly generates 2a5549c0a5a352e01a25bf53463faef13a5ed8e1b86869cc86ffcd8a4fdcde99

I'm checking the SHA256 here http://www.fileformat.info/tool/hash.htm

**Comment by CruiserX** [comment]
I fixed multiblock problem you experienced.
Thanks.

select sha256.ENCRYPT('very very very very very very very very very very very long message') from dual;
==> 0d6930576859630d2254bef86b875767ea2c9e674ad7110ed6882ca263b05194

select sha256.ENCRYPT('very very very very very very very very very very long message') from dual
==> 2a5549c0a5a352e01a25bf53463faef13a5ed8e1b86869cc86ffcd8a4fdcde99

**Comment by chakhdin** [comment]
Thanks for prompt reply.
