### ISSUE TITLE
> 64 length causing ORA-06502: PL/SQL: numeric or value error

### ISSUE THREAD

**Issue by satnam888** [CruiserX/sha256_plsql#5]
installed latest version of package and tested with 64 char string...

select sha256.ENCRYPT('1234567890123456789012345678901234567890123456789012345678901234') from dual;
ORA-06502: PL/SQL: numeric or value error
ORA-06512: at "SYS.UTL_RAW", line 380
ORA-06512: at "SYSTEM.SHA256", line 368
ORA-06512: at "SYSTEM.SHA256", line 522
ORA-06512: at "SYSTEM.SHA256", line 513

although:
select sha256.ENCRYPT('very very very very very very very very very very very long message') from dual;

works fine.

any advise appreciated.

**Comment by CruiserX** [comment]
I fixed 64 length problem.
Thanks.

select sha256.ENCRYPT('1234567890123456789012345678901234567890123456789012345678901234') from dual;
=> 676491965ed3ec50cb7a63ee96315480a95c54426b0b72bca8a0d4ad1285ad55
